version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - 27017:27017
    volumes:
      - collection:/data/db

  web-app:
    build: ./WebApp
    ports:
      - 5001:5001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DBNAME=collection
    depends_on:
      - mongodb
    
volumes:
  collection:
